apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: app-site
images:
- name: app-site
  newName: nandocloud/app-site
  newTag: f85fa20164d9c40c7968b2fe0ab7ef9438cd217c
